= XYZ Reader Starter Code

This repository stores the starter code for the XYZ Reader project in Udacity's Android Nanodegree.

This project was really good for me because I was able to work on my weakest skill which is UI/UX design. The main objective of this project is to make an app's existing UI not only Material Design but also UX friendly. We were given a user feedback to have an idea on how to best fix the app's UI:

User Feedback for XYZ Reader:
Lyla says:
“This app is starting to shape up but it feels a bit off in quite a few places. I can't put finger on it but it feels odd.”

Jay says:
“Is the text supposed to be so wonky and unreadable? It is not accessible to those of us without perfect vision."

Kagure says:
“The color scheme is really sad and I shouldn't feel sad.”

To finish this project I used the following:

Material Design Course at Udacity: 
https://www.udacity.com/course/material-design-for-android-developers--ud862

Material Design Android code lab:
https://codelabs.developers.google.com/codelabs/material-design-style/index.html?index=..%2F..%2Findex#0

To ignore status bar transparency:
https://stackoverflow.com/a/42313556/5104935


